// VayuBot multi-language content — en, hi, ga, ku
export const BOT_LANG = {
  en: {
    welcome: "👋 Hi! I'm **VayuBot**, your VayuWarn assistant.\n\nI can help you with alerts, emergency numbers, how to report disasters, and more.\n\nWhat would you like to know today?",
    chooseTopic: "CHOOSE A TOPIC:",
    suggested: "💡 SUGGESTED QUESTIONS:",
    placeholder: "Ask VayuBot anything...",
    online: "Online • VayuWarn Assistant",
    fallback: "🤔 I'm not sure about that, but here are things I can help with:",
    hello: "👋 Hello! How can I help you today? Choose a topic below or type your question.",
    thanks: "🙏 You're welcome! Stay safe and prepared. Anything else?",
    cats: [
      { id: "what", label: "What is VayuWarn?" },
      { id: "how", label: "How to use the app" },
      { id: "alerts", label: "About Alerts" },
      { id: "numbers", label: "Emergency Numbers" },
      { id: "map", label: "Live Map" },
      { id: "report", label: "Report a Disaster" },
      { id: "safety", label: "Safety Tips" },
    ],
    questions: ["What is VayuWarn?","How do I get real-time alerts?","What emergency numbers should I call?","How do I report a disaster?"],
    answers: {
      what: "🌐 **VayuWarn** is India's community-powered real-time disaster early-warning platform.\n\nIt aggregates crowd-sourced reports, admin-verified alerts, and live geolocation data to warn citizens about floods, landslides, earthquakes, cyclones, and more — in under 1 second.\n\n🏆 Built for climate resilience across India.",
      how: "📱 **Getting Started:**\n\n**Step 1** — Sign up with your email.\n**Step 2** — Allow location for nearby alerts.\n**Step 3** — Browse alerts on the Alerts page and Live Map.\n**Step 4** — Report incidents from the Report page.\n**Step 5** — Share alerts with family and friends.",
      alerts: "🔔 **Alert System:**\n\n• **High** 🔴 — Immediate danger, take action now.\n• **Medium** 🟡 — Be cautious, monitor situation.\n• **Low** 🟢 — Informational, stay aware.\n\nAlerts include location, timestamp, description, and recommended actions. All admin-verified.",
      numbers: "📞 **Emergency Helplines (India):**\n\n• **1078** — National Disaster Helpline\n• **100** — Police\n• **101** — Fire Brigade\n• **108** — Ambulance / NDMA\n• **011-24363260** — NDRF HQ\n• **1800-11-1363** — PM Relief Helpline\n• **112** — Universal Emergency",
      map: "🗺️ **Live Map:**\n\n• 📍 Pinned alerts with color-coded severity\n• 🔴 Pulse rings on high-severity alerts\n• 🗓️ Real-time updates via Firebase\n\nClick any pin for alert details.",
      report: "📝 **To report a disaster:**\n\n1. Go to the **Report** page.\n2. Select disaster type (Flood, Landslide, etc.).\n3. Enter location and description.\n4. Submit — admin team verifies and publishes.\n\n⚡ Reports protect your community in real time!",
      safety: "🛡️ **Safety Tips:**\n\n• Stay calm — panic makes things worse.\n• Keep emergency kit: water, food, torch, first-aid.\n• Know your evacuation route.\n• Save emergency numbers on your phone.\n• Help elderly and disabled neighbours.\n• Do NOT spread unverified information.\n• Follow NDMA advisories.\n\n🆘 In danger, call **112**.",
    },
    keywords: {
      hello: ["hello","hi","hey","hola"],
      thanks: ["thank","thanks","dhanyavad"],
      numbers: ["number","helpline","call","emergency","phone"],
      alerts: ["alert","notification","warning"],
      map: ["map","location","where"],
      report: ["report","submit","file"],
    },
  },
  hi: {
    welcome: "👋 नमस्ते! मैं **वायुबॉट** हूँ, आपका VayuWarn सहायक।\n\nमैं अलर्ट, आपातकालीन नंबर, आपदा रिपोर्ट और बहुत कुछ में मदद कर सकता हूँ।\n\nआज आप क्या जानना चाहेंगे?",
    chooseTopic: "विषय चुनें:",
    suggested: "💡 सुझाए गए प्रश्न:",
    placeholder: "वायुबॉट से कुछ भी पूछें...",
    online: "ऑनलाइन • VayuWarn सहायक",
    fallback: "🤔 मुझे इसके बारे में पक्का नहीं पता, लेकिन ये विषय मदद कर सकते हैं:",
    hello: "👋 नमस्ते! मैं आज आपकी कैसे मदद कर सकता हूँ? नीचे विषय चुनें या अपना प्रश्न लिखें।",
    thanks: "🙏 आपका स्वागत है! सुरक्षित रहें। कुछ और जानना है?",
    cats: [
      { id: "what", label: "VayuWarn क्या है?" },
      { id: "how", label: "ऐप कैसे इस्तेमाल करें" },
      { id: "alerts", label: "अलर्ट के बारे में" },
      { id: "numbers", label: "आपातकालीन नंबर" },
      { id: "map", label: "लाइव नक्शा" },
      { id: "report", label: "आपदा रिपोर्ट करें" },
      { id: "safety", label: "सुरक्षा टिप्स" },
    ],
    questions: ["VayuWarn क्या है?","रियल-टाइम अलर्ट कैसे मिलेंगे?","कौन से आपातकालीन नंबर पर कॉल करें?","आपदा रिपोर्ट कैसे करें?"],
    answers: {
      what: "🌐 **VayuWarn** भारत का समुदाय-संचालित रियल-टाइम आपदा चेतावनी प्लेटफॉर्म है।\n\nयह बाढ़, भूस्खलन, भूकंप, चक्रवात आदि की चेतावनी 1 सेकंड से कम में देता है।\n\n🏆 भारत की जलवायु सुरक्षा के लिए बनाया गया।",
      how: "📱 **शुरू कैसे करें:**\n\n**चरण 1** — ईमेल से साइन अप करें।\n**चरण 2** — लोकेशन अनुमति दें।\n**चरण 3** — अलर्ट पेज और लाइव मैप पर अलर्ट देखें।\n**चरण 4** — रिपोर्ट पेज से घटना रिपोर्ट करें।\n**चरण 5** — परिवार और दोस्तों से शेयर करें।",
      alerts: "🔔 **अलर्ट प्रणाली:**\n\n• **उच्च** 🔴 — तत्काल खतरा, अभी कार्रवाई करें।\n• **मध्यम** 🟡 — सावधान रहें।\n• **कम** 🟢 — जानकारी के लिए।\n\nसभी अलर्ट एडमिन द्वारा सत्यापित हैं।",
      numbers: "📞 **आपातकालीन हेल्पलाइन:**\n\n• **1078** — राष्ट्रीय आपदा हेल्पलाइन\n• **100** — पुलिस\n• **101** — फायर ब्रिगेड\n• **108** — एम्बुलेंस\n• **011-24363260** — NDRF मुख्यालय\n• **1800-11-1363** — PM राहत हेल्पलाइन\n• **112** — सार्वभौमिक आपातकालीन",
      map: "🗺️ **लाइव नक्शा:**\n\n• 📍 रंग-कोडित अलर्ट पिन\n• 🔴 उच्च-गंभीरता पर पल्स रिंग\n• 🗓️ Firebase से रियल-टाइम अपडेट\n\nविवरण के लिए किसी भी पिन पर क्लिक करें।",
      report: "📝 **आपदा रिपोर्ट करने के लिए:**\n\n1. **रिपोर्ट** पेज पर जाएं।\n2. आपदा प्रकार चुनें।\n3. स्थान और विवरण दर्ज करें।\n4. सबमिट करें — एडमिन सत्यापित करेगा।\n\n⚡ आपकी रिपोर्ट समुदाय की रक्षा करती है!",
      safety: "🛡️ **सुरक्षा टिप्स:**\n\n• शांत रहें।\n• आपातकालीन किट रखें: पानी, भोजन, टॉर्च, प्राथमिक चिकित्सा।\n• निकासी मार्ग जानें।\n• आपातकालीन नंबर फोन में सेव करें।\n• बुजुर्गों और विकलांग पड़ोसियों की मदद करें।\n• अनवेरिफाइड जानकारी न फैलाएं।\n\n🆘 खतरे में **112** पर कॉल करें।",
    },
    keywords: {
      hello: ["नमस्ते","हैलो","हाय","hello","hi"],
      thanks: ["धन्यवाद","शुक्रिया","thank"],
      numbers: ["नंबर","हेल्पलाइन","कॉल","आपातकालीन","फोन"],
      alerts: ["अलर्ट","सूचना","चेतावनी"],
      map: ["नक्शा","मैप","कहां","स्थान"],
      report: ["रिपोर्ट","दर्ज","भेज"],
    },
  },
  ga: {
    welcome: "👋 नमस्कार! मैं **वायुबॉट** छूं, तुमरो VayuWarn सहायक।\n\nमैं खबर, आपदा नंबर, रिपोर्ट अर सुरक्षा टिप्स में मदद करि सकदूं।\n\nआज क्या जाणना चांदा?",
    chooseTopic: "विषय चुणो:",
    suggested: "💡 सुझाए गया सवाल:",
    placeholder: "वायुबॉट से कुछ भी पूछो...",
    online: "ऑनलाइन • VayuWarn सहायक",
    fallback: "🤔 यी बारा मैं पक्को नि जाणदूं, पर यी विषय मदद करि सकदन:",
    hello: "👋 नमस्कार! आज कैसे मदद करूं? नीचे विषय चुणो या सवाल लिखो।",
    thanks: "🙏 तुमरो स्वागत छ! सुरक्षित रौ। कुछ और जाणना छ?",
    cats: [
      { id: "what", label: "VayuWarn क्या छ?" },
      { id: "how", label: "ऐप कैसे चलाओ" },
      { id: "alerts", label: "खबर के बारा" },
      { id: "numbers", label: "आपदा नंबर" },
      { id: "map", label: "लाइव नक्शो" },
      { id: "report", label: "आपदा रिपोर्ट करो" },
      { id: "safety", label: "सुरक्षा टिप्स" },
    ],
    questions: ["VayuWarn क्या छ?","रियल-टाइम खबर कैसे मिलली?","कुण सा आपदा नंबर पर कॉल करो?","आपदा रिपोर्ट कैसे करो?"],
    answers: {
      what: "🌐 **VayuWarn** भारत को समुदाय-संचालित रियल-टाइम आपदा चेतावनी प्लेटफॉर्म छ।\n\nयी बाढ़, भूस्खलन, भूकंप, तूफान की खबर 1 सेकंड में दिंदो।\n\n🏔️ उत्तराखंड अर पूरा भारत की सुरक्षा खुणि बणायो गे।",
      how: "📱 **शुरू कैसे करो:**\n\n**1** — ईमेल से साइन अप करो।\n**2** — लोकेशन की अनुमति दियो।\n**3** — खबर पेज अर लाइव नक्शे पर खबर देखो।\n**4** — रिपोर्ट पेज से घटना रिपोर्ट करो।\n**5** — घर वालों अर दोस्तों को बताओ।",
      alerts: "🔔 **खबर प्रणाली:**\n\n• **उच्च** 🔴 — तुरंत खतरा, अभी कार्रवाई करो।\n• **मध्यम** 🟡 — सावधान रौ।\n• **कम** 🟢 — जानकारी खुणि।\n\nसब खबर एडमिन से जांची गई छन।",
      numbers: "📞 **आपदा हेल्पलाइन:**\n\n• **1078** — राष्ट्रीय आपदा हेल्पलाइन\n• **100** — पुलिस\n• **101** — फायर ब्रिगेड\n• **108** — एम्बुलेंस\n• **011-24363260** — NDRF\n• **1800-11-1363** — PM राहत\n• **112** — इमरजेंसी",
      map: "🗺️ **लाइव नक्शो:**\n\n• 📍 रंग-कोड वाली खबर पिन\n• 🔴 उच्च खतरा पर पल्स रिंग\n• 🗓️ Firebase से रियल-टाइम अपडेट\n\nकिसी भी पिन पर क्लिक करो विवरण खुणि।",
      report: "📝 **आपदा रिपोर्ट करण खुणि:**\n\n1. **रिपोर्ट** पेज खोलो।\n2. आपदा का प्रकार चुणो।\n3. जगह अर विवरण लिखो।\n4. भेजो — एडमिन जांच करलो।\n\n⚡ तुमरी रिपोर्ट समुदाय बचांदी!",
      safety: "🛡️ **सुरक्षा टिप्स:**\n\n• शांत रौ।\n• आपदा किट रखो: पाणि, खाणो, टॉर्च।\n• निकासी रास्ता जाणो।\n• आपदा नंबर फोन में रखो।\n• बूढ़ा-बुजुर्ग पड़ोसियों की मदद करो।\n• झूठी खबर मत फैलाओ।\n\n🆘 खतरा पर **112** कॉल करो।",
    },
    keywords: {
      hello: ["नमस्कार","हैलो","हाय","hello","hi"],
      thanks: ["धन्यवाद","शुक्रिया","thank"],
      numbers: ["नंबर","हेल्पलाइन","कॉल","आपदा","फोन"],
      alerts: ["खबर","अलर्ट","चेतावनी"],
      map: ["नक्शो","मैप","कहां","जगह"],
      report: ["रिपोर्ट","भेज","बता"],
    },
  },
  ku: {
    welcome: "👋 नमस्कार! मैं **वायुबॉट** छूँ, तुमरो VayuWarn सहायक।\n\nमैं सूचना, आपद नंबर, रिपोर्ट अर सुरक्षा टिप्स में मदद करि सकनूँ।\n\nआज क्या जाणन चाछा?",
    chooseTopic: "विषय चुणो:",
    suggested: "💡 सुझाए गया सवाल:",
    placeholder: "वायुबॉट से कुछ भी पूछो...",
    online: "ऑनलाइन • VayuWarn सहायक",
    fallback: "🤔 यो बारा मैं पक्को नि जाणनूँ, पर यी विषय मदद करि सकन:",
    hello: "👋 नमस्कार! आज कैसे मदद करूँ? नीचे विषय चुणो या सवाल लिखो।",
    thanks: "🙏 तुमरो स्वागत छ! सुरक्षित रौ। कुछ और जाणन छ?",
    cats: [
      { id: "what", label: "VayuWarn क्या छ?" },
      { id: "how", label: "ऐप कैसे चलाओ" },
      { id: "alerts", label: "सूचना के बारा" },
      { id: "numbers", label: "आपद नंबर" },
      { id: "map", label: "लाइव नक्सो" },
      { id: "report", label: "आपद रिपोर्ट करो" },
      { id: "safety", label: "सुरक्षा टिप्स" },
    ],
    questions: ["VayuWarn क्या छ?","रियल-टाइम सूचना कैसे मिलिहाल?","कुण सा आपद नंबर पर कॉल करो?","आपद रिपोर्ट कैसे करो?"],
    answers: {
      what: "🌐 **VayuWarn** भारत को समुदाय-संचालित रियल-टाइम आपद चेतावनी प्लेटफॉर्म छ।\n\nयो बाढ़, भूस्खलन, भूकंप, तूफान की सूचना 1 सेकंड में दिंछ।\n\n🏔️ कुमाऊँ अर पूरा भारत की सुरक्षा खुणि बणायो गे।",
      how: "📱 **शुरू कैसे करो:**\n\n**1** — ईमेल से साइन अप करो।\n**2** — लोकेशन की अनुमति दियो।\n**3** — सूचना पेज अर लाइव नक्से पर सूचना देखो।\n**4** — रिपोर्ट पेज से घटना रिपोर्ट करो।\n**5** — घर वालों अर दोस्तों ले बताओ।",
      alerts: "🔔 **सूचना प्रणाली:**\n\n• **उच्च** 🔴 — तुरंत खतर, अभी कार्रवाई करो।\n• **मध्यम** 🟡 — सावधान रौ।\n• **कम** 🟢 — जानकारी खुणि।\n\nसब सूचना एडमिन से जांची गई छन।",
      numbers: "📞 **आपद हेल्पलाइन:**\n\n• **1078** — राष्ट्रीय आपद हेल्पलाइन\n• **100** — पुलिस\n• **101** — फायर ब्रिगेड\n• **108** — एम्बुलेंस\n• **011-24363260** — NDRF\n• **1800-11-1363** — PM राहत\n• **112** — इमरजेंसी",
      map: "🗺️ **लाइव नक्सो:**\n\n• 📍 रंग-कोड वाली सूचना पिन\n• 🔴 उच्च खतर पर पल्स रिंग\n• 🗓️ Firebase से रियल-टाइम अपडेट\n\nकिसी भी पिन पर क्लिक करो विवरण खुणि।",
      report: "📝 **आपद रिपोर्ट करण खुणि:**\n\n1. **रिपोर्ट** पेज खोलो।\n2. आपद का प्रकार चुणो।\n3. जगह अर विवरण लिखो।\n4. भेजो — एडमिन जाँच करलो।\n\n⚡ तुमरी रिपोर्ट समुदाय बचांछ!",
      safety: "🛡️ **सुरक्षा टिप्स:**\n\n• शांत रौ।\n• आपद किट रखो: पाणि, खाणो, टॉर्च।\n• निकासी रास्ता जाणो।\n• आपद नंबर फोन में रखो।\n• बुजुर्ग पड़ोसियों की मदद करो।\n• झूठी सूचना मत फैलाओ।\n\n🆘 खतर पर **112** कॉल करो।",
    },
    keywords: {
      hello: ["नमस्कार","हैलो","हाय","hello","hi"],
      thanks: ["धन्यवाद","शुक्रिया","thank"],
      numbers: ["नंबर","हेल्पलाइन","कॉल","आपद","फोन"],
      alerts: ["सूचना","अलर्ट","चेतावनी"],
      map: ["नक्सो","मैप","कहां","जगह"],
      report: ["रिपोर्ट","भेज","बता"],
    },
  },
};
